# Site settings
title:  Slate
email: slate@shopify.com
description: > # this means to ignore newlines until "baseurl:"
  Slate is a theme scaffold and command line tool for developing Shopify themes. It is designed to assist your development workflow and speed up the process of developing, testing, and deploying themes to Shopify stores.
baseurl: "/slate"
url: "https://shopify.github.io"
sass:
  cache: true
source: docs

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
